### ISSUE TITLE
Token Verification not working on stats endpoint

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#110]
Token verification not working on stats endpoints for some reason.  @GDave50 add the error you get when you try to add the `VerifyToken` middleware to the routes.

**Comment by GDave50** [comment]
![error](https://user-images.githubusercontent.com/29603332/36998312-77527a72-208a-11e8-9b74-2e77675cacbb.png)

**Comment by landonp1203** [comment]
@GDave50 Give the solution that you told me, and reference this issue in the PR that fixes it.
