### ISSUE TITLE
ScoresDB needs to be updated

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#133]
Update on this is below...

**Comment by landonp1203** [comment]
@CSC480-18S/red-database Update on this?

**Comment by landonp1203** [comment]
After talking with DB, we are changing the way the ScoresDB works:

- Now  going with the idea of having the ScoresDB only tracks the stats of the tiles, rather than their respective scores as Engine has decided to not go with dynamic tile updating.
- Engine will send data in the following format so that the ScoresDB can update the tile usages accordingly:

```
[
    {
        "letter": "a"
    },
    {
        "letter": "q"
    }
]
```

**Comment by landonp1203** [comment]
@DKear @sha224 @samwheeler2014 @kpemblet Update on this is above^

**Comment by LandonPatmore** [comment]
Closed as this was decided to not be needed.
