### ISSUE TITLE
Need a get all users in game endpoint

### ISSUE THREAD

**Issue by cking20** [CSC480-18S/Red-Team#142]
I need to get all the Players in the game in JSON format. I'll need all the variables of Player.js as well as there should be another bool variable added called something like "isAI" to denote if that player is an AI. Also the order in which the Players are sent back matters. The order should be consistent with the way they are represented in the Game-manager or where ever the backend keeps track of the user's array

**Comment by landonp1203** [comment]
@cking20 Can you give me the format you want? In JSON please.

**Comment by landonp1203** [comment]
Implemented.
