### ISSUE TITLE
Bad words valid words discrepancy

### ISSUE THREAD

**Issue by cesarbiods** [CSC480-18S/Red-Team#173]
The valid words dictionary and the invalid words dictionary have differences in the number of permutations per word, leading to bad words being able to be played on the game, which would cause Bastian to fall out of his chair. These differences have to be worked out at some point, at least before May 4th.
@cking20 can answer technical questions if I can't answer them.

**Comment by LandonPatmore** [comment]
@hreitmei @hkobrien Can we find a smaller dictionary? This will help slim down our memory footprint on both the DB and Server Frontend for the AI.  This will also help us with bad word mitigation.  There will also be more "coherent" words for players and AI to choose, not BS.

Here are some links to some dictionaries that I found:
- [Google 10000 Most Common Words](https://github.com/first20hours/google-10000-english)
- [Word Lists](https://www.wordfrequency.info/free.asp)
