### ISSUE TITLE
Start word position validation

### ISSUE THREAD

**Issue by James-Aric** [CSC480-18S/Red-Team#188]
When playing a two letter word as first word on empty board, more often then not frontend receives a INVALID_PLACEMENT error

**Comment by James-Aric** [comment]
[
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, "a", "h", null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null],
	[null, null, null, null, null, null, null, null, null, null, null]
]

returns an INVALID_PLACEMENT

**Comment by James-Aric** [comment]
got play
{"reason":"INVALID PLACEMENT","invalid":true,"word":"AH"}

**Comment by landonp1203** [comment]
Fixed with new letter and word validations.
