### ISSUE TITLE
Frontend and AI disconnect from backend

### ISSUE THREAD

**Issue by James-Aric** [CSC480-18S/Red-Team#201]
After a certain period of time (ranging from 1-2 minutes) the AI frontend and AI entities receive EVENT_DISCONNECT for no discernible reason. This may be due to the heartbeat timeout, which is when the server pings the client periodically to check if the client is still alive. I tried setting the timeout to infinite, which fixed nothing. Only thought is that the client and server connection gets interrupted by something. Possibly need to throw time intensive calculations into a separate thread in order to keep the heartbeat alive?

**Comment by landonp1203** [comment]
Have we figured this out yet? @James-Aric

**Comment by LandonPatmore** [comment]
Has this been fixed?
