### ISSUE TITLE
AI sending garbage to server

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#204]
Towards the later stages of the game, when the AI are trying to think of words to play, they seem to be sending garbage plays to the server.  A lot of garbage gets sent.  Will need to hunt it down, but saw it when I glanced at the console at a moment.

This could actual be part of the bug in #201 .

**Comment by James-Aric** [comment]
Can you give me an example and can you recreate it?

**Comment by LandonPatmore** [comment]
Cannot reproduce as of now

**Comment by LandonPatmore** [comment]
Have not seen this, will reopen if the issue pops up again.
