### ISSUE TITLE
Implement newGameCountdown event

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#214]
This event will:

- send out timer that is decremented every 1000 milliseconds (1 second)
- show the user the timer until the next game
- will be sent out with the `gameOver` event
- everything on the frontend needs to be disabled at this point
- when the timer resets, the client will get a `board` and `dataUpdate` events to reset all data and to make a new game

**Comment by LandonPatmore** [comment]
Done on the backend.

**Comment by LandonPatmore** [comment]
This will now only be sent to the Server Frontend.  A `gameEvent` event will take its place for the clients' devices and shows in the game event box.
