### ISSUE TITLE
Layout developmental work/figure out what needs to be built

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Red-Team#22]

**Comment by landonp1203** [comment]
![alt-text](https://cdn.discordapp.com/attachments/405963090291851264/410582615415062528/JPEG_20180206_184700.jpg)

Work divided amongst teams shown in this picture.

**Comment by BrendanOswego** [comment]
Can this image be formalized in something such as draw.io for learnability, and understandability?

**Comment by landonp1203** [comment]
@BrendanOswego do you want an image of a draw.io visualization, or a link to it? Or both?

**Comment by BrendanOswego** [comment]
If you can add the image to the Assets that would be good, so the team can see without needing to go to google drive

**Comment by landonp1203** [comment]
@BrendanOswego Wouldn't this fall more under just the sprint itself? In the sense of it doesn't contribute anything to the repo?

**Comment by landonp1203** [comment]
Actually I will add this to the wiki, perfect, so it doesn't clutter the repo's code and I can link to it from here.

**Comment by BrendanOswego** [comment]
that's fine as well, I was thinking of other ways to do this and that makes the most sense

**Comment by landonp1203** [comment]
[Wiki page where information is](https://github.com/CSC480-18S/Red-Team/wiki/Tech-Stack)

**Comment by BrendanOswego** [comment]
Thank you for that formality, looks good.
