### ISSUE TITLE
AI missing plays where whole new word is played next to existing tile

### ISSUE THREAD

**Issue by cking20** [CSC480-18S/Red-Team#220]
The algorithm as it currently stands only plays new tiles off of existing tiles. this means that if there is a vertical word going up to the row before the top row, it will never play a horizontal word in the top most row
example: CAT will never be played horizontally in the top row
"-,-,-,-,-"
"-,-,-,a,-"
"-,-,-,n,-"

**Comment by cking20** [comment]
not sure if we should fix this, it could increase the complexity of the algorithm by 4x

**Comment by LandonPatmore** [comment]
Closing as has been chosen to be abandoned. The AI play properly.
