### ISSUE TITLE
Don't allow more than 4 players to join

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#226]
Need to not allow players to connect to the game when 4 players are already playing.

**Comment by LandonPatmore** [comment]
As of now, when any more than 4 people join, the game board shows an alert that there are max players, and they don't get a set of tiles. Still shows them an updating board and game events, they just cannot play.

Need to implement in the login page to redirect them back if they try to join when max players are there.

**Comment by LandonPatmore** [comment]
Closing for now as this is mitigated based on the above comment.
