### ISSUE TITLE
Discussing and laying out API endpoints

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Red-Team#24]

**Comment by landonp1203** [comment]
Link to Google Sheets that houses our proposed API endpoints, will transfer them over to the wiki once they are done so they can be fully documented outside of just looking at the source code:

https://docs.google.com/spreadsheets/d/1-FnU9ilG1Z28ZnQSYfiXnA7wx6j7RLANFqMnGyQrICE/edit?usp=sharing

**Comment by BrendanOswego** [comment]
Thank you for documentation, this is enough to close issue.

**Comment by sNoeIIe** [comment]
(backend) - API Endpoints
