### ISSUE TITLE
Develop 5 conceptual layouts (mobile/monitor)

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Red-Team#25]

**Comment by xmorton** [comment]
Completed and verified, concepts can be found in the Assets folder.

**Comment by landonp1203** [comment]
Here is a link to the `Concepts` folder as of commit https://github.com/CSC480-18s/Red-Team/commit/8bd7c8dc84764cdd0b17f023a27eb138d6423db7:

[Concepts Folder](https://github.com/CSC480-18S/Red-Team/tree/8bd7c8dc84764cdd0b17f023a27eb138d6423db7/Assets/Concepts)

**Comment by sNoeIIe** [comment]
(GUI) - Conceptual Development
