### ISSUE TITLE
Play a turn timer bug

### ISSUE THREAD

**Issue by cesarbiods** [CSC480-18S/Red-Team#276]
The timer counts too fast and goes negative without skipping the user's turn.

**Comment by LandonPatmore** [comment]
This is an issue with the `setInterval` timer, I could not figure it out with the time constraints before the demo.

**Comment by LandonPatmore** [comment]
This was being sent from the backend before, but was changed to the frontend at the last minute.  I will reimplement the timer to send to the frontend now that we are slimming down our stack.
