### ISSUE TITLE
B1.4   User Registration[Username/Mac Bind]

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Red-Team#29]
- Does the DB contain user registration information? Most likely does not have to
communicate with Engine yet unless Engine is ready and Red DB has the time.

**Comment by BrendanOswego** [comment]
This will be implemented at a later sprint.

**Comment by landonp1203** [comment]
@cesarbiods comment/reference this issue from a PR when you get this working.

**Comment by cesarbiods** [comment]
This was done in PR #121
