### ISSUE TITLE
A2.2   Building API endpoints

### ISSUE THREAD

**Issue by BrendanOswego** [CSC480-18S/Red-Team#30]

**Comment by landonp1203** [comment]
Link to Google Sheets that houses our proposed API endpoints, will transfer them over to the wiki once they are done so they can be fully documented outside of just looking at the source code:

https://docs.google.com/spreadsheets/d/1-FnU9ilG1Z28ZnQSYfiXnA7wx6j7RLANFqMnGyQrICE/edit?usp=sharing

**Comment by sNoeIIe** [comment]
(Backend) - API Endpoints

**Comment by cesarbiods** [comment]
Without the database endpoints I'm not sure this will get done in time?

**Comment by landonp1203** [comment]
Moved this task on the Gantt chart to March 9th as completion date.  This will roll into other weeks, but this should be just for initial implementation of routes.
