### ISSUE TITLE
Bonus words not appearing on GameDB

### ISSUE THREAD

**Issue by cesarbiods** [CSC480-18S/Red-Team#311]
When a user plays a bonus word you see the goose flying (laughs hysterically), but the database does not store the special word.
This likely means the server backend is not sending the word to be stored as a special in the gameDB, otherwise there is a bug on the DB.

**Comment by sha224** [comment]
Just double checked. It looks like GameDB is storing the special words and it also appears in frequentlySpecialPlayedWords field of the Team. Make sure that the Engine is sending it to the database.
