### ISSUE TITLE
GUI: Mobile Client Resizing

### ISSUE THREAD

**Issue by samwheeler2014** [CSC480-18S/Red-Team#337]
As it currently is, the mobile client is too big to properly fit on anyone's phone screen, even newer and bigger phone screens. The entire mobile client display should more properly fit on most phone screens such that users don't have to scroll on their phone to see the entire display (from "You are {username} at the top, to the entirety of the Exchange, Done, and Shuffle buttons at the bottom). This should be accomplished by reducing spacing between elements on the page (for example, less space between the timer and the user's hand).

**Comment by LandonPatmore** [comment]
Fixed.
