### ISSUE TITLE
AI Team Balancing

### ISSUE THREAD

**Issue by brendangoldberg** [CSC480-18S/Red-Team#340]
Currently, there could be 4 Gold team AI players. [link to demo](https://drive.google.com/file/d/1wIvBACtVTZAgHpG6BljvQW9iuKmQ1MyA/view?usp=sharing)

**Comment by LandonPatmore** [comment]
This is not an issue. Their teams are randomly generated.

**Comment by brendangoldberg** [comment]
This should fall under a game balancing issue, if people are able to look into this, then great, if not, it can be closed by end of semester.

**Comment by LandonPatmore** [comment]
Fixed, teams for AI are now staggered like: `Green, Gold, Green, Gold` and are in a FIFO queue.  When a AI connects, they grab the first one, and when they leave they push it to the back of the queue.
