### ISSUE TITLE
JSON Standardization

### ISSUE THREAD

**Issue by landonp1203** [CSC480-18S/Red-Team#87]
Each JSON response needs to have a standardized response across all API calls.

Going to follow the [JSON API](http://jsonapi.org/format/1.0/) v1.0 standard.

Each Response must have the following:
- `metadata` object: data that is not critical to the response (license, author, api version, etc.)
- ** `data` object: data that is critical to the response (actual json response with the requested data)
- **`errors` object: data that is critical to a failed response (error code, message, status code)

Bullet points with `**` means that these objects cannot coexist in the same response.

**Comment by rzsupra17** [comment]
Issue related to #88 Json standardization which was already approved and closed.
